import express, { Response, Request } from "express" ;
import cookieParser from "cookie-parser";
import userRouter from "./modules/user/user.routes";
import authRouter from "./modules/auth/auth.routes";
export const app = express() ;
app.use(express.json()) ;
app.use(cookieParser()) ;
app.use('/api/v1',userRouter) ;
app.use('/api/v1',authRouter) ;
export default app ;